name: Node.js CI

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - run: npm ci
      - run: npm test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.1.0
        with:
          files: ./coverage/lcov.info
          verbose: true
          fail_ci_if_error: true
